### ISSUE TITLE
Missing GregTech?

### ISSUE THREAD

**Issue by minimalistjack** [PurplikDev/Thaumicbound#1]
Not sure if this is a bug but when I check it out I don't see any GregTech

**Comment by PurplikDev** [comment]
Could you send me your crash report? So far it seems like a bug

**Comment by minimalistjack** [comment]
Sure,
https://pastebin.com/CyFGPBWY

**Comment by PurplikDev** [comment]
Oh, it seems like you have a skill issue. I am sorry but I can't help you with that.

**Comment by minimalistjack** [comment]
Ratio
